//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.11.10 at 09:10:55 AM CET 
//


package org.mesa.xml.b2mml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for InformationObjectType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="InformationObjectType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice>
 *           &lt;element name="OperationalLocation" type="{http://www.mesa.org/xml/B2MML}OperationalLocationType"/>
 *           &lt;element name="OperationalLocationClass" type="{http://www.mesa.org/xml/B2MML}OperationalLocationClassType"/>
 *           &lt;element name="PersonnelClass" type="{http://www.mesa.org/xml/B2MML}PersonnelClassType"/>
 *           &lt;element name="Person" type="{http://www.mesa.org/xml/B2MML}PersonType"/>
 *           &lt;element name="EquipmentClass" type="{http://www.mesa.org/xml/B2MML}EquipmentClassType"/>
 *           &lt;element name="Equipment" type="{http://www.mesa.org/xml/B2MML}EquipmentType"/>
 *           &lt;element name="PhysicalAssetClass" type="{http://www.mesa.org/xml/B2MML}PhysicalAssetClassType"/>
 *           &lt;element name="PhysicalAsset" type="{http://www.mesa.org/xml/B2MML}PhysicalAssetType"/>
 *           &lt;element name="MaterialClass" type="{http://www.mesa.org/xml/B2MML}MaterialClassType"/>
 *           &lt;element name="MaterialDefinition" type="{http://www.mesa.org/xml/B2MML}MaterialDefinitionType"/>
 *           &lt;element name="MaterialLot" type="{http://www.mesa.org/xml/B2MML}MaterialLotType"/>
 *           &lt;element name="MaterialSubLot" type="{http://www.mesa.org/xml/B2MML}MaterialSubLotType"/>
 *           &lt;element name="ProcessSegment" type="{http://www.mesa.org/xml/B2MML}ProcessSegmentType"/>
 *           &lt;element name="TestSpecification" type="{http://www.mesa.org/xml/B2MML}TestSpecificationType"/>
 *           &lt;element name="TestResult" type="{http://www.mesa.org/xml/B2MML}TestResultType"/>
 *           &lt;element name="OperationsEventClass" type="{http://www.mesa.org/xml/B2MML}OperationsEventClassType"/>
 *           &lt;element name="OperationsEventDefinition" type="{http://www.mesa.org/xml/B2MML}OperationsEventDefinitionType"/>
 *           &lt;element name="OperationsEvent" type="{http://www.mesa.org/xml/B2MML}OperationsEventType"/>
 *           &lt;element name="OperationsDefinition" type="{http://www.mesa.org/xml/B2MML}OperationsDefinitionType"/>
 *           &lt;element name="OperationsSegment" type="{http://www.mesa.org/xml/B2MML}OperationsSegmentType"/>
 *           &lt;element name="OperationsSchedule" type="{http://www.mesa.org/xml/B2MML}OperationsScheduleType"/>
 *           &lt;element name="OperationsRequest" type="{http://www.mesa.org/xml/B2MML}OperationsRequestType"/>
 *           &lt;element name="OperationsPerformance" type="{http://www.mesa.org/xml/B2MML}OperationsPerformanceType"/>
 *           &lt;element name="OperationsResponse" type="{http://www.mesa.org/xml/B2MML}OperationsResponseType"/>
 *           &lt;element name="OperationsCapability" type="{http://www.mesa.org/xml/B2MML}OperationsCapabilityType"/>
 *           &lt;element name="ResourceRelationshipNetwork" type="{http://www.mesa.org/xml/B2MML}ResourceRelationshipNetworkType"/>
 *           &lt;element name="ResourceNetworkConnectionType" type="{http://www.mesa.org/xml/B2MML}ResourceNetworkConnectionTypeType"/>
 *           &lt;element name="WorkMaster" type="{http://www.mesa.org/xml/B2MML}WorkMasterType"/>
 *           &lt;element name="WorkDirective" type="{http://www.mesa.org/xml/B2MML}WorkDirectiveType"/>
 *           &lt;element name="WorkflowSpecification" type="{http://www.mesa.org/xml/B2MML}WorkflowSpecificationType"/>
 *           &lt;element name="WorkflowSpecificationNodeType" type="{http://www.mesa.org/xml/B2MML}WorkflowSpecificationNodeTypeType"/>
 *           &lt;element name="WorkflowSpecificationConnectionType" type="{http://www.mesa.org/xml/B2MML}WorkflowSpecificationConnectionTypeType"/>
 *           &lt;element name="WorkSchedule" type="{http://www.mesa.org/xml/B2MML}WorkScheduleType"/>
 *           &lt;element name="WorkRequest" type="{http://www.mesa.org/xml/B2MML}WorkRequestType"/>
 *           &lt;element name="JobList" type="{http://www.mesa.org/xml/B2MML}JobListType"/>
 *           &lt;element name="JobOrder" type="{http://www.mesa.org/xml/B2MML}JobOrderType"/>
 *           &lt;element name="WorkPerformance" type="{http://www.mesa.org/xml/B2MML}WorkPerformanceType"/>
 *           &lt;element name="WorkResponse" type="{http://www.mesa.org/xml/B2MML}WorkResponseType"/>
 *           &lt;element name="JobResponse" type="{http://www.mesa.org/xml/B2MML}JobResponseType"/>
 *           &lt;element name="JobResponseList" type="{http://www.mesa.org/xml/B2MML}JobResponseListType"/>
 *           &lt;element name="WorkCapability" type="{http://www.mesa.org/xml/B2MML}WorkCapabilityType"/>
 *           &lt;element name="WorkMasterCapability" type="{http://www.mesa.org/xml/B2MML}WorkMasterCapabilityType"/>
 *           &lt;element name="WorkAlertDefinition" type="{http://www.mesa.org/xml/B2MML}WorkAlertDefinitionType"/>
 *           &lt;element name="WorkAlert" type="{http://www.mesa.org/xml/B2MML}WorkAlertType"/>
 *           &lt;element name="WorkCalendar" type="{http://www.mesa.org/xml/B2MML}WorkCalendarType"/>
 *           &lt;element name="WorkCalendarDefinition" type="{http://www.mesa.org/xml/B2MML}WorkCalendarDefinitionType"/>
 *           &lt;element name="WorkRecord" type="{http://www.mesa.org/xml/B2MML}WorkRecordType"/>
 *           &lt;element name="WorkRecordSpecification" type="{http://www.mesa.org/xml/B2MML}WorkRecordSpecificationType"/>
 *           &lt;element name="BatchProductionRecord" type="{http://www.mesa.org/xml/B2MML}BatchProductionRecordType"/>
 *           &lt;element name="GRecipe" type="{http://www.mesa.org/xml/B2MML}GRecipeType"/>
 *           &lt;element name="ResourceConstraint" type="{http://www.mesa.org/xml/B2MML}ResourceConstraintType"/>
 *           &lt;element name="ProcessElement" type="{http://www.mesa.org/xml/B2MML}ProcessElementType"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "InformationObjectType", propOrder = {
    "operationalLocation",
    "operationalLocationClass",
    "personnelClass",
    "person",
    "equipmentClass",
    "equipment",
    "physicalAssetClass",
    "physicalAsset",
    "materialClass",
    "materialDefinition",
    "materialLot",
    "materialSubLot",
    "processSegment",
    "testSpecification",
    "testResult",
    "operationsEventClass",
    "operationsEventDefinition",
    "operationsEvent",
    "operationsDefinition",
    "operationsSegment",
    "operationsSchedule",
    "operationsRequest",
    "operationsPerformance",
    "operationsResponse",
    "operationsCapability",
    "resourceRelationshipNetwork",
    "resourceNetworkConnectionType",
    "workMaster",
    "workDirective",
    "workflowSpecification",
    "workflowSpecificationNodeType",
    "workflowSpecificationConnectionType",
    "workSchedule",
    "workRequest",
    "jobList",
    "jobOrder",
    "workPerformance",
    "workResponse",
    "jobResponse",
    "jobResponseList",
    "workCapability",
    "workMasterCapability",
    "workAlertDefinition",
    "workAlert",
    "workCalendar",
    "workCalendarDefinition",
    "workRecord",
    "workRecordSpecification",
    "batchProductionRecord",
    "gRecipe",
    "resourceConstraint",
    "processElement"
})
public class InformationObjectType {

    @XmlElement(name = "OperationalLocation", namespace = "")
    protected OperationalLocationType operationalLocation;
    @XmlElement(name = "OperationalLocationClass", namespace = "")
    protected OperationalLocationClassType operationalLocationClass;
    @XmlElement(name = "PersonnelClass", namespace = "")
    protected PersonnelClassType personnelClass;
    @XmlElement(name = "Person", namespace = "")
    protected PersonType person;
    @XmlElement(name = "EquipmentClass", namespace = "")
    protected EquipmentClassType equipmentClass;
    @XmlElement(name = "Equipment", namespace = "")
    protected EquipmentType equipment;
    @XmlElement(name = "PhysicalAssetClass", namespace = "")
    protected PhysicalAssetClassType physicalAssetClass;
    @XmlElement(name = "PhysicalAsset", namespace = "")
    protected PhysicalAssetType physicalAsset;
    @XmlElement(name = "MaterialClass", namespace = "")
    protected MaterialClassType materialClass;
    @XmlElement(name = "MaterialDefinition", namespace = "")
    protected MaterialDefinitionType materialDefinition;
    @XmlElement(name = "MaterialLot", namespace = "")
    protected MaterialLotType materialLot;
    @XmlElement(name = "MaterialSubLot", namespace = "")
    protected MaterialSubLotType materialSubLot;
    @XmlElement(name = "ProcessSegment", namespace = "")
    protected ProcessSegmentType processSegment;
    @XmlElement(name = "TestSpecification", namespace = "")
    protected TestSpecificationType testSpecification;
    @XmlElement(name = "TestResult", namespace = "")
    protected TestResultType testResult;
    @XmlElement(name = "OperationsEventClass", namespace = "")
    protected OperationsEventClassType operationsEventClass;
    @XmlElement(name = "OperationsEventDefinition", namespace = "")
    protected OperationsEventDefinitionType operationsEventDefinition;
    @XmlElement(name = "OperationsEvent", namespace = "")
    protected OperationsEventType operationsEvent;
    @XmlElement(name = "OperationsDefinition", namespace = "")
    protected OperationsDefinitionType operationsDefinition;
    @XmlElement(name = "OperationsSegment", namespace = "")
    protected OperationsSegmentType operationsSegment;
    @XmlElement(name = "OperationsSchedule", namespace = "")
    protected OperationsScheduleType operationsSchedule;
    @XmlElement(name = "OperationsRequest", namespace = "")
    protected OperationsRequestType operationsRequest;
    @XmlElement(name = "OperationsPerformance", namespace = "")
    protected OperationsPerformanceType operationsPerformance;
    @XmlElement(name = "OperationsResponse", namespace = "")
    protected OperationsResponseType operationsResponse;
    @XmlElement(name = "OperationsCapability", namespace = "")
    protected OperationsCapabilityType operationsCapability;
    @XmlElement(name = "ResourceRelationshipNetwork", namespace = "")
    protected ResourceRelationshipNetworkType resourceRelationshipNetwork;
    @XmlElement(name = "ResourceNetworkConnectionType", namespace = "")
    protected ResourceNetworkConnectionTypeType resourceNetworkConnectionType;
    @XmlElement(name = "WorkMaster", namespace = "")
    protected WorkMasterType workMaster;
    @XmlElement(name = "WorkDirective", namespace = "")
    protected WorkDirectiveType workDirective;
    @XmlElement(name = "WorkflowSpecification", namespace = "")
    protected WorkflowSpecificationType workflowSpecification;
    @XmlElement(name = "WorkflowSpecificationNodeType", namespace = "")
    protected WorkflowSpecificationNodeTypeType workflowSpecificationNodeType;
    @XmlElement(name = "WorkflowSpecificationConnectionType", namespace = "")
    protected WorkflowSpecificationConnectionTypeType workflowSpecificationConnectionType;
    @XmlElement(name = "WorkSchedule", namespace = "")
    protected WorkScheduleType workSchedule;
    @XmlElement(name = "WorkRequest", namespace = "")
    protected WorkRequestType workRequest;
    @XmlElement(name = "JobList", namespace = "")
    protected JobListType jobList;
    @XmlElement(name = "JobOrder", namespace = "")
    protected JobOrderType jobOrder;
    @XmlElement(name = "WorkPerformance", namespace = "")
    protected WorkPerformanceType workPerformance;
    @XmlElement(name = "WorkResponse", namespace = "")
    protected WorkResponseType workResponse;
    @XmlElement(name = "JobResponse", namespace = "")
    protected JobResponseType jobResponse;
    @XmlElement(name = "JobResponseList", namespace = "")
    protected JobResponseListType jobResponseList;
    @XmlElement(name = "WorkCapability", namespace = "")
    protected WorkCapabilityType workCapability;
    @XmlElement(name = "WorkMasterCapability", namespace = "")
    protected WorkMasterCapabilityType workMasterCapability;
    @XmlElement(name = "WorkAlertDefinition", namespace = "")
    protected WorkAlertDefinitionType workAlertDefinition;
    @XmlElement(name = "WorkAlert", namespace = "")
    protected WorkAlertType workAlert;
    @XmlElement(name = "WorkCalendar", namespace = "")
    protected WorkCalendarType workCalendar;
    @XmlElement(name = "WorkCalendarDefinition", namespace = "")
    protected WorkCalendarDefinitionType workCalendarDefinition;
    @XmlElement(name = "WorkRecord", namespace = "")
    protected WorkRecordType workRecord;
    @XmlElement(name = "WorkRecordSpecification", namespace = "")
    protected WorkRecordSpecificationType workRecordSpecification;
    @XmlElement(name = "BatchProductionRecord", namespace = "")
    protected BatchProductionRecordType batchProductionRecord;
    @XmlElement(name = "GRecipe", namespace = "")
    protected GRecipeType gRecipe;
    @XmlElement(name = "ResourceConstraint", namespace = "")
    protected ResourceConstraintType resourceConstraint;
    @XmlElement(name = "ProcessElement", namespace = "")
    protected ProcessElementType processElement;

    /**
     * Gets the value of the operationalLocation property.
     * 
     * @return
     *     possible object is
     *     {@link OperationalLocationType }
     *     
     */
    public OperationalLocationType getOperationalLocation() {
        return operationalLocation;
    }

    /**
     * Sets the value of the operationalLocation property.
     * 
     * @param value
     *     allowed object is
     *     {@link OperationalLocationType }
     *     
     */
    public void setOperationalLocation(OperationalLocationType value) {
        this.operationalLocation = value;
    }

    /**
     * Gets the value of the operationalLocationClass property.
     * 
     * @return
     *     possible object is
     *     {@link OperationalLocationClassType }
     *     
     */
    public OperationalLocationClassType getOperationalLocationClass() {
        return operationalLocationClass;
    }

    /**
     * Sets the value of the operationalLocationClass property.
     * 
     * @param value
     *     allowed object is
     *     {@link OperationalLocationClassType }
     *     
     */
    public void setOperationalLocationClass(OperationalLocationClassType value) {
        this.operationalLocationClass = value;
    }

    /**
     * Gets the value of the personnelClass property.
     * 
     * @return
     *     possible object is
     *     {@link PersonnelClassType }
     *     
     */
    public PersonnelClassType getPersonnelClass() {
        return personnelClass;
    }

    /**
     * Sets the value of the personnelClass property.
     * 
     * @param value
     *     allowed object is
     *     {@link PersonnelClassType }
     *     
     */
    public void setPersonnelClass(PersonnelClassType value) {
        this.personnelClass = value;
    }

    /**
     * Gets the value of the person property.
     * 
     * @return
     *     possible object is
     *     {@link PersonType }
     *     
     */
    public PersonType getPerson() {
        return person;
    }

    /**
     * Sets the value of the person property.
     * 
     * @param value
     *     allowed object is
     *     {@link PersonType }
     *     
     */
    public void setPerson(PersonType value) {
        this.person = value;
    }

    /**
     * Gets the value of the equipmentClass property.
     * 
     * @return
     *     possible object is
     *     {@link EquipmentClassType }
     *     
     */
    public EquipmentClassType getEquipmentClass() {
        return equipmentClass;
    }

    /**
     * Sets the value of the equipmentClass property.
     * 
     * @param value
     *     allowed object is
     *     {@link EquipmentClassType }
     *     
     */
    public void setEquipmentClass(EquipmentClassType value) {
        this.equipmentClass = value;
    }

    /**
     * Gets the value of the equipment property.
     * 
     * @return
     *     possible object is
     *     {@link EquipmentType }
     *     
     */
    public EquipmentType getEquipment() {
        return equipment;
    }

    /**
     * Sets the value of the equipment property.
     * 
     * @param value
     *     allowed object is
     *     {@link EquipmentType }
     *     
     */
    public void setEquipment(EquipmentType value) {
        this.equipment = value;
    }

    /**
     * Gets the value of the physicalAssetClass property.
     * 
     * @return
     *     possible object is
     *     {@link PhysicalAssetClassType }
     *     
     */
    public PhysicalAssetClassType getPhysicalAssetClass() {
        return physicalAssetClass;
    }

    /**
     * Sets the value of the physicalAssetClass property.
     * 
     * @param value
     *     allowed object is
     *     {@link PhysicalAssetClassType }
     *     
     */
    public void setPhysicalAssetClass(PhysicalAssetClassType value) {
        this.physicalAssetClass = value;
    }

    /**
     * Gets the value of the physicalAsset property.
     * 
     * @return
     *     possible object is
     *     {@link PhysicalAssetType }
     *     
     */
    public PhysicalAssetType getPhysicalAsset() {
        return physicalAsset;
    }

    /**
     * Sets the value of the physicalAsset property.
     * 
     * @param value
     *     allowed object is
     *     {@link PhysicalAssetType }
     *     
     */
    public void setPhysicalAsset(PhysicalAssetType value) {
        this.physicalAsset = value;
    }

    /**
     * Gets the value of the materialClass property.
     * 
     * @return
     *     possible object is
     *     {@link MaterialClassType }
     *     
     */
    public MaterialClassType getMaterialClass() {
        return materialClass;
    }

    /**
     * Sets the value of the materialClass property.
     * 
     * @param value
     *     allowed object is
     *     {@link MaterialClassType }
     *     
     */
    public void setMaterialClass(MaterialClassType value) {
        this.materialClass = value;
    }

    /**
     * Gets the value of the materialDefinition property.
     * 
     * @return
     *     possible object is
     *     {@link MaterialDefinitionType }
     *     
     */
    public MaterialDefinitionType getMaterialDefinition() {
        return materialDefinition;
    }

    /**
     * Sets the value of the materialDefinition property.
     * 
     * @param value
     *     allowed object is
     *     {@link MaterialDefinitionType }
     *     
     */
    public void setMaterialDefinition(MaterialDefinitionType value) {
        this.materialDefinition = value;
    }

    /**
     * Gets the value of the materialLot property.
     * 
     * @return
     *     possible object is
     *     {@link MaterialLotType }
     *     
     */
    public MaterialLotType getMaterialLot() {
        return materialLot;
    }

    /**
     * Sets the value of the materialLot property.
     * 
     * @param value
     *     allowed object is
     *     {@link MaterialLotType }
     *     
     */
    public void setMaterialLot(MaterialLotType value) {
        this.materialLot = value;
    }

    /**
     * Gets the value of the materialSubLot property.
     * 
     * @return
     *     possible object is
     *     {@link MaterialSubLotType }
     *     
     */
    public MaterialSubLotType getMaterialSubLot() {
        return materialSubLot;
    }

    /**
     * Sets the value of the materialSubLot property.
     * 
     * @param value
     *     allowed object is
     *     {@link MaterialSubLotType }
     *     
     */
    public void setMaterialSubLot(MaterialSubLotType value) {
        this.materialSubLot = value;
    }

    /**
     * Gets the value of the processSegment property.
     * 
     * @return
     *     possible object is
     *     {@link ProcessSegmentType }
     *     
     */
    public ProcessSegmentType getProcessSegment() {
        return processSegment;
    }

    /**
     * Sets the value of the processSegment property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProcessSegmentType }
     *     
     */
    public void setProcessSegment(ProcessSegmentType value) {
        this.processSegment = value;
    }

    /**
     * Gets the value of the testSpecification property.
     * 
     * @return
     *     possible object is
     *     {@link TestSpecificationType }
     *     
     */
    public TestSpecificationType getTestSpecification() {
        return testSpecification;
    }

    /**
     * Sets the value of the testSpecification property.
     * 
     * @param value
     *     allowed object is
     *     {@link TestSpecificationType }
     *     
     */
    public void setTestSpecification(TestSpecificationType value) {
        this.testSpecification = value;
    }

    /**
     * Gets the value of the testResult property.
     * 
     * @return
     *     possible object is
     *     {@link TestResultType }
     *     
     */
    public TestResultType getTestResult() {
        return testResult;
    }

    /**
     * Sets the value of the testResult property.
     * 
     * @param value
     *     allowed object is
     *     {@link TestResultType }
     *     
     */
    public void setTestResult(TestResultType value) {
        this.testResult = value;
    }

    /**
     * Gets the value of the operationsEventClass property.
     * 
     * @return
     *     possible object is
     *     {@link OperationsEventClassType }
     *     
     */
    public OperationsEventClassType getOperationsEventClass() {
        return operationsEventClass;
    }

    /**
     * Sets the value of the operationsEventClass property.
     * 
     * @param value
     *     allowed object is
     *     {@link OperationsEventClassType }
     *     
     */
    public void setOperationsEventClass(OperationsEventClassType value) {
        this.operationsEventClass = value;
    }

    /**
     * Gets the value of the operationsEventDefinition property.
     * 
     * @return
     *     possible object is
     *     {@link OperationsEventDefinitionType }
     *     
     */
    public OperationsEventDefinitionType getOperationsEventDefinition() {
        return operationsEventDefinition;
    }

    /**
     * Sets the value of the operationsEventDefinition property.
     * 
     * @param value
     *     allowed object is
     *     {@link OperationsEventDefinitionType }
     *     
     */
    public void setOperationsEventDefinition(OperationsEventDefinitionType value) {
        this.operationsEventDefinition = value;
    }

    /**
     * Gets the value of the operationsEvent property.
     * 
     * @return
     *     possible object is
     *     {@link OperationsEventType }
     *     
     */
    public OperationsEventType getOperationsEvent() {
        return operationsEvent;
    }

    /**
     * Sets the value of the operationsEvent property.
     * 
     * @param value
     *     allowed object is
     *     {@link OperationsEventType }
     *     
     */
    public void setOperationsEvent(OperationsEventType value) {
        this.operationsEvent = value;
    }

    /**
     * Gets the value of the operationsDefinition property.
     * 
     * @return
     *     possible object is
     *     {@link OperationsDefinitionType }
     *     
     */
    public OperationsDefinitionType getOperationsDefinition() {
        return operationsDefinition;
    }

    /**
     * Sets the value of the operationsDefinition property.
     * 
     * @param value
     *     allowed object is
     *     {@link OperationsDefinitionType }
     *     
     */
    public void setOperationsDefinition(OperationsDefinitionType value) {
        this.operationsDefinition = value;
    }

    /**
     * Gets the value of the operationsSegment property.
     * 
     * @return
     *     possible object is
     *     {@link OperationsSegmentType }
     *     
     */
    public OperationsSegmentType getOperationsSegment() {
        return operationsSegment;
    }

    /**
     * Sets the value of the operationsSegment property.
     * 
     * @param value
     *     allowed object is
     *     {@link OperationsSegmentType }
     *     
     */
    public void setOperationsSegment(OperationsSegmentType value) {
        this.operationsSegment = value;
    }

    /**
     * Gets the value of the operationsSchedule property.
     * 
     * @return
     *     possible object is
     *     {@link OperationsScheduleType }
     *     
     */
    public OperationsScheduleType getOperationsSchedule() {
        return operationsSchedule;
    }

    /**
     * Sets the value of the operationsSchedule property.
     * 
     * @param value
     *     allowed object is
     *     {@link OperationsScheduleType }
     *     
     */
    public void setOperationsSchedule(OperationsScheduleType value) {
        this.operationsSchedule = value;
    }

    /**
     * Gets the value of the operationsRequest property.
     * 
     * @return
     *     possible object is
     *     {@link OperationsRequestType }
     *     
     */
    public OperationsRequestType getOperationsRequest() {
        return operationsRequest;
    }

    /**
     * Sets the value of the operationsRequest property.
     * 
     * @param value
     *     allowed object is
     *     {@link OperationsRequestType }
     *     
     */
    public void setOperationsRequest(OperationsRequestType value) {
        this.operationsRequest = value;
    }

    /**
     * Gets the value of the operationsPerformance property.
     * 
     * @return
     *     possible object is
     *     {@link OperationsPerformanceType }
     *     
     */
    public OperationsPerformanceType getOperationsPerformance() {
        return operationsPerformance;
    }

    /**
     * Sets the value of the operationsPerformance property.
     * 
     * @param value
     *     allowed object is
     *     {@link OperationsPerformanceType }
     *     
     */
    public void setOperationsPerformance(OperationsPerformanceType value) {
        this.operationsPerformance = value;
    }

    /**
     * Gets the value of the operationsResponse property.
     * 
     * @return
     *     possible object is
     *     {@link OperationsResponseType }
     *     
     */
    public OperationsResponseType getOperationsResponse() {
        return operationsResponse;
    }

    /**
     * Sets the value of the operationsResponse property.
     * 
     * @param value
     *     allowed object is
     *     {@link OperationsResponseType }
     *     
     */
    public void setOperationsResponse(OperationsResponseType value) {
        this.operationsResponse = value;
    }

    /**
     * Gets the value of the operationsCapability property.
     * 
     * @return
     *     possible object is
     *     {@link OperationsCapabilityType }
     *     
     */
    public OperationsCapabilityType getOperationsCapability() {
        return operationsCapability;
    }

    /**
     * Sets the value of the operationsCapability property.
     * 
     * @param value
     *     allowed object is
     *     {@link OperationsCapabilityType }
     *     
     */
    public void setOperationsCapability(OperationsCapabilityType value) {
        this.operationsCapability = value;
    }

    /**
     * Gets the value of the resourceRelationshipNetwork property.
     * 
     * @return
     *     possible object is
     *     {@link ResourceRelationshipNetworkType }
     *     
     */
    public ResourceRelationshipNetworkType getResourceRelationshipNetwork() {
        return resourceRelationshipNetwork;
    }

    /**
     * Sets the value of the resourceRelationshipNetwork property.
     * 
     * @param value
     *     allowed object is
     *     {@link ResourceRelationshipNetworkType }
     *     
     */
    public void setResourceRelationshipNetwork(ResourceRelationshipNetworkType value) {
        this.resourceRelationshipNetwork = value;
    }

    /**
     * Gets the value of the resourceNetworkConnectionType property.
     * 
     * @return
     *     possible object is
     *     {@link ResourceNetworkConnectionTypeType }
     *     
     */
    public ResourceNetworkConnectionTypeType getResourceNetworkConnectionType() {
        return resourceNetworkConnectionType;
    }

    /**
     * Sets the value of the resourceNetworkConnectionType property.
     * 
     * @param value
     *     allowed object is
     *     {@link ResourceNetworkConnectionTypeType }
     *     
     */
    public void setResourceNetworkConnectionType(ResourceNetworkConnectionTypeType value) {
        this.resourceNetworkConnectionType = value;
    }

    /**
     * Gets the value of the workMaster property.
     * 
     * @return
     *     possible object is
     *     {@link WorkMasterType }
     *     
     */
    public WorkMasterType getWorkMaster() {
        return workMaster;
    }

    /**
     * Sets the value of the workMaster property.
     * 
     * @param value
     *     allowed object is
     *     {@link WorkMasterType }
     *     
     */
    public void setWorkMaster(WorkMasterType value) {
        this.workMaster = value;
    }

    /**
     * Gets the value of the workDirective property.
     * 
     * @return
     *     possible object is
     *     {@link WorkDirectiveType }
     *     
     */
    public WorkDirectiveType getWorkDirective() {
        return workDirective;
    }

    /**
     * Sets the value of the workDirective property.
     * 
     * @param value
     *     allowed object is
     *     {@link WorkDirectiveType }
     *     
     */
    public void setWorkDirective(WorkDirectiveType value) {
        this.workDirective = value;
    }

    /**
     * Gets the value of the workflowSpecification property.
     * 
     * @return
     *     possible object is
     *     {@link WorkflowSpecificationType }
     *     
     */
    public WorkflowSpecificationType getWorkflowSpecification() {
        return workflowSpecification;
    }

    /**
     * Sets the value of the workflowSpecification property.
     * 
     * @param value
     *     allowed object is
     *     {@link WorkflowSpecificationType }
     *     
     */
    public void setWorkflowSpecification(WorkflowSpecificationType value) {
        this.workflowSpecification = value;
    }

    /**
     * Gets the value of the workflowSpecificationNodeType property.
     * 
     * @return
     *     possible object is
     *     {@link WorkflowSpecificationNodeTypeType }
     *     
     */
    public WorkflowSpecificationNodeTypeType getWorkflowSpecificationNodeType() {
        return workflowSpecificationNodeType;
    }

    /**
     * Sets the value of the workflowSpecificationNodeType property.
     * 
     * @param value
     *     allowed object is
     *     {@link WorkflowSpecificationNodeTypeType }
     *     
     */
    public void setWorkflowSpecificationNodeType(WorkflowSpecificationNodeTypeType value) {
        this.workflowSpecificationNodeType = value;
    }

    /**
     * Gets the value of the workflowSpecificationConnectionType property.
     * 
     * @return
     *     possible object is
     *     {@link WorkflowSpecificationConnectionTypeType }
     *     
     */
    public WorkflowSpecificationConnectionTypeType getWorkflowSpecificationConnectionType() {
        return workflowSpecificationConnectionType;
    }

    /**
     * Sets the value of the workflowSpecificationConnectionType property.
     * 
     * @param value
     *     allowed object is
     *     {@link WorkflowSpecificationConnectionTypeType }
     *     
     */
    public void setWorkflowSpecificationConnectionType(WorkflowSpecificationConnectionTypeType value) {
        this.workflowSpecificationConnectionType = value;
    }

    /**
     * Gets the value of the workSchedule property.
     * 
     * @return
     *     possible object is
     *     {@link WorkScheduleType }
     *     
     */
    public WorkScheduleType getWorkSchedule() {
        return workSchedule;
    }

    /**
     * Sets the value of the workSchedule property.
     * 
     * @param value
     *     allowed object is
     *     {@link WorkScheduleType }
     *     
     */
    public void setWorkSchedule(WorkScheduleType value) {
        this.workSchedule = value;
    }

    /**
     * Gets the value of the workRequest property.
     * 
     * @return
     *     possible object is
     *     {@link WorkRequestType }
     *     
     */
    public WorkRequestType getWorkRequest() {
        return workRequest;
    }

    /**
     * Sets the value of the workRequest property.
     * 
     * @param value
     *     allowed object is
     *     {@link WorkRequestType }
     *     
     */
    public void setWorkRequest(WorkRequestType value) {
        this.workRequest = value;
    }

    /**
     * Gets the value of the jobList property.
     * 
     * @return
     *     possible object is
     *     {@link JobListType }
     *     
     */
    public JobListType getJobList() {
        return jobList;
    }

    /**
     * Sets the value of the jobList property.
     * 
     * @param value
     *     allowed object is
     *     {@link JobListType }
     *     
     */
    public void setJobList(JobListType value) {
        this.jobList = value;
    }

    /**
     * Gets the value of the jobOrder property.
     * 
     * @return
     *     possible object is
     *     {@link JobOrderType }
     *     
     */
    public JobOrderType getJobOrder() {
        return jobOrder;
    }

    /**
     * Sets the value of the jobOrder property.
     * 
     * @param value
     *     allowed object is
     *     {@link JobOrderType }
     *     
     */
    public void setJobOrder(JobOrderType value) {
        this.jobOrder = value;
    }

    /**
     * Gets the value of the workPerformance property.
     * 
     * @return
     *     possible object is
     *     {@link WorkPerformanceType }
     *     
     */
    public WorkPerformanceType getWorkPerformance() {
        return workPerformance;
    }

    /**
     * Sets the value of the workPerformance property.
     * 
     * @param value
     *     allowed object is
     *     {@link WorkPerformanceType }
     *     
     */
    public void setWorkPerformance(WorkPerformanceType value) {
        this.workPerformance = value;
    }

    /**
     * Gets the value of the workResponse property.
     * 
     * @return
     *     possible object is
     *     {@link WorkResponseType }
     *     
     */
    public WorkResponseType getWorkResponse() {
        return workResponse;
    }

    /**
     * Sets the value of the workResponse property.
     * 
     * @param value
     *     allowed object is
     *     {@link WorkResponseType }
     *     
     */
    public void setWorkResponse(WorkResponseType value) {
        this.workResponse = value;
    }

    /**
     * Gets the value of the jobResponse property.
     * 
     * @return
     *     possible object is
     *     {@link JobResponseType }
     *     
     */
    public JobResponseType getJobResponse() {
        return jobResponse;
    }

    /**
     * Sets the value of the jobResponse property.
     * 
     * @param value
     *     allowed object is
     *     {@link JobResponseType }
     *     
     */
    public void setJobResponse(JobResponseType value) {
        this.jobResponse = value;
    }

    /**
     * Gets the value of the jobResponseList property.
     * 
     * @return
     *     possible object is
     *     {@link JobResponseListType }
     *     
     */
    public JobResponseListType getJobResponseList() {
        return jobResponseList;
    }

    /**
     * Sets the value of the jobResponseList property.
     * 
     * @param value
     *     allowed object is
     *     {@link JobResponseListType }
     *     
     */
    public void setJobResponseList(JobResponseListType value) {
        this.jobResponseList = value;
    }

    /**
     * Gets the value of the workCapability property.
     * 
     * @return
     *     possible object is
     *     {@link WorkCapabilityType }
     *     
     */
    public WorkCapabilityType getWorkCapability() {
        return workCapability;
    }

    /**
     * Sets the value of the workCapability property.
     * 
     * @param value
     *     allowed object is
     *     {@link WorkCapabilityType }
     *     
     */
    public void setWorkCapability(WorkCapabilityType value) {
        this.workCapability = value;
    }

    /**
     * Gets the value of the workMasterCapability property.
     * 
     * @return
     *     possible object is
     *     {@link WorkMasterCapabilityType }
     *     
     */
    public WorkMasterCapabilityType getWorkMasterCapability() {
        return workMasterCapability;
    }

    /**
     * Sets the value of the workMasterCapability property.
     * 
     * @param value
     *     allowed object is
     *     {@link WorkMasterCapabilityType }
     *     
     */
    public void setWorkMasterCapability(WorkMasterCapabilityType value) {
        this.workMasterCapability = value;
    }

    /**
     * Gets the value of the workAlertDefinition property.
     * 
     * @return
     *     possible object is
     *     {@link WorkAlertDefinitionType }
     *     
     */
    public WorkAlertDefinitionType getWorkAlertDefinition() {
        return workAlertDefinition;
    }

    /**
     * Sets the value of the workAlertDefinition property.
     * 
     * @param value
     *     allowed object is
     *     {@link WorkAlertDefinitionType }
     *     
     */
    public void setWorkAlertDefinition(WorkAlertDefinitionType value) {
        this.workAlertDefinition = value;
    }

    /**
     * Gets the value of the workAlert property.
     * 
     * @return
     *     possible object is
     *     {@link WorkAlertType }
     *     
     */
    public WorkAlertType getWorkAlert() {
        return workAlert;
    }

    /**
     * Sets the value of the workAlert property.
     * 
     * @param value
     *     allowed object is
     *     {@link WorkAlertType }
     *     
     */
    public void setWorkAlert(WorkAlertType value) {
        this.workAlert = value;
    }

    /**
     * Gets the value of the workCalendar property.
     * 
     * @return
     *     possible object is
     *     {@link WorkCalendarType }
     *     
     */
    public WorkCalendarType getWorkCalendar() {
        return workCalendar;
    }

    /**
     * Sets the value of the workCalendar property.
     * 
     * @param value
     *     allowed object is
     *     {@link WorkCalendarType }
     *     
     */
    public void setWorkCalendar(WorkCalendarType value) {
        this.workCalendar = value;
    }

    /**
     * Gets the value of the workCalendarDefinition property.
     * 
     * @return
     *     possible object is
     *     {@link WorkCalendarDefinitionType }
     *     
     */
    public WorkCalendarDefinitionType getWorkCalendarDefinition() {
        return workCalendarDefinition;
    }

    /**
     * Sets the value of the workCalendarDefinition property.
     * 
     * @param value
     *     allowed object is
     *     {@link WorkCalendarDefinitionType }
     *     
     */
    public void setWorkCalendarDefinition(WorkCalendarDefinitionType value) {
        this.workCalendarDefinition = value;
    }

    /**
     * Gets the value of the workRecord property.
     * 
     * @return
     *     possible object is
     *     {@link WorkRecordType }
     *     
     */
    public WorkRecordType getWorkRecord() {
        return workRecord;
    }

    /**
     * Sets the value of the workRecord property.
     * 
     * @param value
     *     allowed object is
     *     {@link WorkRecordType }
     *     
     */
    public void setWorkRecord(WorkRecordType value) {
        this.workRecord = value;
    }

    /**
     * Gets the value of the workRecordSpecification property.
     * 
     * @return
     *     possible object is
     *     {@link WorkRecordSpecificationType }
     *     
     */
    public WorkRecordSpecificationType getWorkRecordSpecification() {
        return workRecordSpecification;
    }

    /**
     * Sets the value of the workRecordSpecification property.
     * 
     * @param value
     *     allowed object is
     *     {@link WorkRecordSpecificationType }
     *     
     */
    public void setWorkRecordSpecification(WorkRecordSpecificationType value) {
        this.workRecordSpecification = value;
    }

    /**
     * Gets the value of the batchProductionRecord property.
     * 
     * @return
     *     possible object is
     *     {@link BatchProductionRecordType }
     *     
     */
    public BatchProductionRecordType getBatchProductionRecord() {
        return batchProductionRecord;
    }

    /**
     * Sets the value of the batchProductionRecord property.
     * 
     * @param value
     *     allowed object is
     *     {@link BatchProductionRecordType }
     *     
     */
    public void setBatchProductionRecord(BatchProductionRecordType value) {
        this.batchProductionRecord = value;
    }

    /**
     * Gets the value of the gRecipe property.
     * 
     * @return
     *     possible object is
     *     {@link GRecipeType }
     *     
     */
    public GRecipeType getGRecipe() {
        return gRecipe;
    }

    /**
     * Sets the value of the gRecipe property.
     * 
     * @param value
     *     allowed object is
     *     {@link GRecipeType }
     *     
     */
    public void setGRecipe(GRecipeType value) {
        this.gRecipe = value;
    }

    /**
     * Gets the value of the resourceConstraint property.
     * 
     * @return
     *     possible object is
     *     {@link ResourceConstraintType }
     *     
     */
    public ResourceConstraintType getResourceConstraint() {
        return resourceConstraint;
    }

    /**
     * Sets the value of the resourceConstraint property.
     * 
     * @param value
     *     allowed object is
     *     {@link ResourceConstraintType }
     *     
     */
    public void setResourceConstraint(ResourceConstraintType value) {
        this.resourceConstraint = value;
    }

    /**
     * Gets the value of the processElement property.
     * 
     * @return
     *     possible object is
     *     {@link ProcessElementType }
     *     
     */
    public ProcessElementType getProcessElement() {
        return processElement;
    }

    /**
     * Sets the value of the processElement property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProcessElementType }
     *     
     */
    public void setProcessElement(ProcessElementType value) {
        this.processElement = value;
    }

}
