//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.11.10 at 09:10:55 AM CET 
//


package org.mesa.xml.b2mml;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for OperationsRecordEntryTemplateType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="OperationsRecordEntryTemplateType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ID" type="{http://www.mesa.org/xml/B2MML}IdentifierType"/>
 *         &lt;element name="Description" type="{http://www.mesa.org/xml/B2MML}DescriptionType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Version" type="{http://www.mesa.org/xml/B2MML}IdentifierType" minOccurs="0"/>
 *         &lt;element name="RecordTimestamp" type="{http://www.mesa.org/xml/B2MML}DateTimeType" minOccurs="0"/>
 *         &lt;element name="EffectiveTimestamp" type="{http://www.mesa.org/xml/B2MML}DateTimeType" minOccurs="0"/>
 *         &lt;element name="EffectiveEndDate" type="{http://www.mesa.org/xml/B2MML}DateTimeType" minOccurs="0"/>
 *         &lt;element name="HierarchyScope" type="{http://www.mesa.org/xml/B2MML}HierarchyScopeType" minOccurs="0"/>
 *         &lt;choice>
 *           &lt;element name="InformationObject" type="{http://www.mesa.org/xml/B2MML}InformationObjectType"/>
 *           &lt;element name="ExternalReferenceID" type="{http://www.mesa.org/xml/B2MML}IdentifierType"/>
 *         &lt;/choice>
 *         &lt;element name="InformationObjectType" type="{http://www.mesa.org/xml/B2MML}InformationObjectTypeType" minOccurs="0"/>
 *         &lt;element name="OperationsRecordEntryChild" type="{http://www.mesa.org/xml/B2MML}OperationsRecordEntryTemplateType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;group ref="{http://www.mesa.org/xml/B2MML-AllExtensions}OperationsRecordEntryTemplate" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OperationsRecordEntryTemplateType", propOrder = {
    "id",
    "description",
    "version",
    "recordTimestamp",
    "effectiveTimestamp",
    "effectiveEndDate",
    "hierarchyScope",
    "informationObject",
    "externalReferenceID",
    "informationObjectType",
    "operationsRecordEntryChild"
})
public class OperationsRecordEntryTemplateType {

    @XmlElement(name = "ID", required = true)
    protected IdentifierType id;
    @XmlElement(name = "Description")
    protected List<DescriptionType> description;
    @XmlElement(name = "Version")
    protected IdentifierType version;
    @XmlElement(name = "RecordTimestamp")
    protected DateTimeType recordTimestamp;
    @XmlElement(name = "EffectiveTimestamp")
    protected DateTimeType effectiveTimestamp;
    @XmlElement(name = "EffectiveEndDate")
    protected DateTimeType effectiveEndDate;
    @XmlElement(name = "HierarchyScope")
    protected HierarchyScopeType hierarchyScope;
    @XmlElement(name = "InformationObject")
    protected InformationObjectType informationObject;
    @XmlElement(name = "ExternalReferenceID")
    protected IdentifierType externalReferenceID;
    @XmlElement(name = "InformationObjectType")
    protected InformationObjectTypeType informationObjectType;
    @XmlElement(name = "OperationsRecordEntryChild")
    protected List<OperationsRecordEntryTemplateType> operationsRecordEntryChild;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link IdentifierType }
     *     
     */
    public IdentifierType getID() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link IdentifierType }
     *     
     */
    public void setID(IdentifierType value) {
        this.id = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the description property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDescription().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DescriptionType }
     * 
     * 
     */
    public List<DescriptionType> getDescription() {
        if (description == null) {
            description = new ArrayList<DescriptionType>();
        }
        return this.description;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link IdentifierType }
     *     
     */
    public IdentifierType getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link IdentifierType }
     *     
     */
    public void setVersion(IdentifierType value) {
        this.version = value;
    }

    /**
     * Gets the value of the recordTimestamp property.
     * 
     * @return
     *     possible object is
     *     {@link DateTimeType }
     *     
     */
    public DateTimeType getRecordTimestamp() {
        return recordTimestamp;
    }

    /**
     * Sets the value of the recordTimestamp property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateTimeType }
     *     
     */
    public void setRecordTimestamp(DateTimeType value) {
        this.recordTimestamp = value;
    }

    /**
     * Gets the value of the effectiveTimestamp property.
     * 
     * @return
     *     possible object is
     *     {@link DateTimeType }
     *     
     */
    public DateTimeType getEffectiveTimestamp() {
        return effectiveTimestamp;
    }

    /**
     * Sets the value of the effectiveTimestamp property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateTimeType }
     *     
     */
    public void setEffectiveTimestamp(DateTimeType value) {
        this.effectiveTimestamp = value;
    }

    /**
     * Gets the value of the effectiveEndDate property.
     * 
     * @return
     *     possible object is
     *     {@link DateTimeType }
     *     
     */
    public DateTimeType getEffectiveEndDate() {
        return effectiveEndDate;
    }

    /**
     * Sets the value of the effectiveEndDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateTimeType }
     *     
     */
    public void setEffectiveEndDate(DateTimeType value) {
        this.effectiveEndDate = value;
    }

    /**
     * Gets the value of the hierarchyScope property.
     * 
     * @return
     *     possible object is
     *     {@link HierarchyScopeType }
     *     
     */
    public HierarchyScopeType getHierarchyScope() {
        return hierarchyScope;
    }

    /**
     * Sets the value of the hierarchyScope property.
     * 
     * @param value
     *     allowed object is
     *     {@link HierarchyScopeType }
     *     
     */
    public void setHierarchyScope(HierarchyScopeType value) {
        this.hierarchyScope = value;
    }

    /**
     * Gets the value of the informationObject property.
     * 
     * @return
     *     possible object is
     *     {@link InformationObjectType }
     *     
     */
    public InformationObjectType getInformationObject() {
        return informationObject;
    }

    /**
     * Sets the value of the informationObject property.
     * 
     * @param value
     *     allowed object is
     *     {@link InformationObjectType }
     *     
     */
    public void setInformationObject(InformationObjectType value) {
        this.informationObject = value;
    }

    /**
     * Gets the value of the externalReferenceID property.
     * 
     * @return
     *     possible object is
     *     {@link IdentifierType }
     *     
     */
    public IdentifierType getExternalReferenceID() {
        return externalReferenceID;
    }

    /**
     * Sets the value of the externalReferenceID property.
     * 
     * @param value
     *     allowed object is
     *     {@link IdentifierType }
     *     
     */
    public void setExternalReferenceID(IdentifierType value) {
        this.externalReferenceID = value;
    }

    /**
     * Gets the value of the informationObjectType property.
     * 
     * @return
     *     possible object is
     *     {@link InformationObjectTypeType }
     *     
     */
    public InformationObjectTypeType getInformationObjectType() {
        return informationObjectType;
    }

    /**
     * Sets the value of the informationObjectType property.
     * 
     * @param value
     *     allowed object is
     *     {@link InformationObjectTypeType }
     *     
     */
    public void setInformationObjectType(InformationObjectTypeType value) {
        this.informationObjectType = value;
    }

    /**
     * Gets the value of the operationsRecordEntryChild property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the operationsRecordEntryChild property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOperationsRecordEntryChild().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link OperationsRecordEntryTemplateType }
     * 
     * 
     */
    public List<OperationsRecordEntryTemplateType> getOperationsRecordEntryChild() {
        if (operationsRecordEntryChild == null) {
            operationsRecordEntryChild = new ArrayList<OperationsRecordEntryTemplateType>();
        }
        return this.operationsRecordEntryChild;
    }

}
