//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.11.10 at 09:10:55 AM CET 
//


package org.mesa.xml.b2mml;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for OperationsEventDefinitionType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="OperationsEventDefinitionType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ID" type="{http://www.mesa.org/xml/B2MML}IdentifierType"/>
 *         &lt;element name="Description" type="{http://www.mesa.org/xml/B2MML}DescriptionType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Version" type="{http://www.mesa.org/xml/B2MML}IdentifierType" minOccurs="0"/>
 *         &lt;element name="PublishedDate" type="{http://www.mesa.org/xml/B2MML}DateTimeType" minOccurs="0"/>
 *         &lt;element name="EffectiveStartDate" type="{http://www.mesa.org/xml/B2MML}DateTimeType" minOccurs="0"/>
 *         &lt;element name="EffectiveEndDate" type="{http://www.mesa.org/xml/B2MML}DateTimeType" minOccurs="0"/>
 *         &lt;element name="HierarchyScope" type="{http://www.mesa.org/xml/B2MML}HierarchyScopeType" minOccurs="0"/>
 *         &lt;element name="Priority" type="{http://www.mesa.org/xml/B2MML}NumericType" minOccurs="0"/>
 *         &lt;element name="OperationsEventType" type="{http://www.mesa.org/xml/B2MML}OperationsEventTypeType" minOccurs="0"/>
 *         &lt;element name="OperationsEventLevel" type="{http://www.mesa.org/xml/B2MML}OperationsEventLevelType" minOccurs="0"/>
 *         &lt;element name="OperationsType" type="{http://www.mesa.org/xml/B2MML}OperationsTypeType" minOccurs="0"/>
 *         &lt;element name="MOMFunction" type="{http://www.mesa.org/xml/B2MML}MOMFunctionType" minOccurs="0"/>
 *         &lt;element name="EnterpriseFunction" type="{http://www.mesa.org/xml/B2MML}EnterpriseFunctionType" minOccurs="0"/>
 *         &lt;element name="Category" type="{http://www.mesa.org/xml/B2MML}IdentifierType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Acknowledgement" type="{http://www.mesa.org/xml/B2MML}IdentifierType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Source" type="{http://www.mesa.org/xml/B2MML}IdentifierType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="OperationsEventDefinitionChild" type="{http://www.mesa.org/xml/B2MML}OperationsEventDefinitionType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="OperationsEventDefinitionProperty" type="{http://www.mesa.org/xml/B2MML}OperationsEventClassPropertyType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="OperationsEventClassID" type="{http://www.mesa.org/xml/B2MML}IdentifierType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="OpsEventDefinitionRecordSpecification" type="{http://www.mesa.org/xml/B2MML}OperationsRecordSpecTemplateType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;group ref="{http://www.mesa.org/xml/B2MML-AllExtensions}OperationsEventDefinition" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OperationsEventDefinitionType", propOrder = {
    "id",
    "description",
    "version",
    "publishedDate",
    "effectiveStartDate",
    "effectiveEndDate",
    "hierarchyScope",
    "priority",
    "operationsEventType",
    "operationsEventLevel",
    "operationsType",
    "momFunction",
    "enterpriseFunction",
    "category",
    "acknowledgement",
    "source",
    "operationsEventDefinitionChild",
    "operationsEventDefinitionProperty",
    "operationsEventClassID",
    "opsEventDefinitionRecordSpecification"
})
public class OperationsEventDefinitionType {

    @XmlElement(name = "ID", required = true)
    protected IdentifierType id;
    @XmlElement(name = "Description")
    protected List<DescriptionType> description;
    @XmlElement(name = "Version")
    protected IdentifierType version;
    @XmlElement(name = "PublishedDate")
    protected DateTimeType publishedDate;
    @XmlElement(name = "EffectiveStartDate")
    protected DateTimeType effectiveStartDate;
    @XmlElement(name = "EffectiveEndDate")
    protected DateTimeType effectiveEndDate;
    @XmlElement(name = "HierarchyScope")
    protected HierarchyScopeType hierarchyScope;
    @XmlElement(name = "Priority")
    protected NumericType priority;
    @XmlElement(name = "OperationsEventType")
    protected OperationsEventTypeType operationsEventType;
    @XmlElement(name = "OperationsEventLevel")
    protected OperationsEventLevelType operationsEventLevel;
    @XmlElement(name = "OperationsType")
    protected OperationsTypeType operationsType;
    @XmlElement(name = "MOMFunction")
    protected MOMFunctionType momFunction;
    @XmlElement(name = "EnterpriseFunction")
    protected EnterpriseFunctionType enterpriseFunction;
    @XmlElement(name = "Category")
    protected List<IdentifierType> category;
    @XmlElement(name = "Acknowledgement")
    protected List<IdentifierType> acknowledgement;
    @XmlElement(name = "Source")
    protected List<IdentifierType> source;
    @XmlElement(name = "OperationsEventDefinitionChild")
    protected List<OperationsEventDefinitionType> operationsEventDefinitionChild;
    @XmlElement(name = "OperationsEventDefinitionProperty")
    protected List<OperationsEventClassPropertyType> operationsEventDefinitionProperty;
    @XmlElement(name = "OperationsEventClassID")
    protected List<IdentifierType> operationsEventClassID;
    @XmlElement(name = "OpsEventDefinitionRecordSpecification")
    protected List<OperationsRecordSpecTemplateType> opsEventDefinitionRecordSpecification;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link IdentifierType }
     *     
     */
    public IdentifierType getID() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link IdentifierType }
     *     
     */
    public void setID(IdentifierType value) {
        this.id = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the description property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDescription().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DescriptionType }
     * 
     * 
     */
    public List<DescriptionType> getDescription() {
        if (description == null) {
            description = new ArrayList<DescriptionType>();
        }
        return this.description;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link IdentifierType }
     *     
     */
    public IdentifierType getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link IdentifierType }
     *     
     */
    public void setVersion(IdentifierType value) {
        this.version = value;
    }

    /**
     * Gets the value of the publishedDate property.
     * 
     * @return
     *     possible object is
     *     {@link DateTimeType }
     *     
     */
    public DateTimeType getPublishedDate() {
        return publishedDate;
    }

    /**
     * Sets the value of the publishedDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateTimeType }
     *     
     */
    public void setPublishedDate(DateTimeType value) {
        this.publishedDate = value;
    }

    /**
     * Gets the value of the effectiveStartDate property.
     * 
     * @return
     *     possible object is
     *     {@link DateTimeType }
     *     
     */
    public DateTimeType getEffectiveStartDate() {
        return effectiveStartDate;
    }

    /**
     * Sets the value of the effectiveStartDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateTimeType }
     *     
     */
    public void setEffectiveStartDate(DateTimeType value) {
        this.effectiveStartDate = value;
    }

    /**
     * Gets the value of the effectiveEndDate property.
     * 
     * @return
     *     possible object is
     *     {@link DateTimeType }
     *     
     */
    public DateTimeType getEffectiveEndDate() {
        return effectiveEndDate;
    }

    /**
     * Sets the value of the effectiveEndDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateTimeType }
     *     
     */
    public void setEffectiveEndDate(DateTimeType value) {
        this.effectiveEndDate = value;
    }

    /**
     * Gets the value of the hierarchyScope property.
     * 
     * @return
     *     possible object is
     *     {@link HierarchyScopeType }
     *     
     */
    public HierarchyScopeType getHierarchyScope() {
        return hierarchyScope;
    }

    /**
     * Sets the value of the hierarchyScope property.
     * 
     * @param value
     *     allowed object is
     *     {@link HierarchyScopeType }
     *     
     */
    public void setHierarchyScope(HierarchyScopeType value) {
        this.hierarchyScope = value;
    }

    /**
     * Gets the value of the priority property.
     * 
     * @return
     *     possible object is
     *     {@link NumericType }
     *     
     */
    public NumericType getPriority() {
        return priority;
    }

    /**
     * Sets the value of the priority property.
     * 
     * @param value
     *     allowed object is
     *     {@link NumericType }
     *     
     */
    public void setPriority(NumericType value) {
        this.priority = value;
    }

    /**
     * Gets the value of the operationsEventType property.
     * 
     * @return
     *     possible object is
     *     {@link OperationsEventTypeType }
     *     
     */
    public OperationsEventTypeType getOperationsEventType() {
        return operationsEventType;
    }

    /**
     * Sets the value of the operationsEventType property.
     * 
     * @param value
     *     allowed object is
     *     {@link OperationsEventTypeType }
     *     
     */
    public void setOperationsEventType(OperationsEventTypeType value) {
        this.operationsEventType = value;
    }

    /**
     * Gets the value of the operationsEventLevel property.
     * 
     * @return
     *     possible object is
     *     {@link OperationsEventLevelType }
     *     
     */
    public OperationsEventLevelType getOperationsEventLevel() {
        return operationsEventLevel;
    }

    /**
     * Sets the value of the operationsEventLevel property.
     * 
     * @param value
     *     allowed object is
     *     {@link OperationsEventLevelType }
     *     
     */
    public void setOperationsEventLevel(OperationsEventLevelType value) {
        this.operationsEventLevel = value;
    }

    /**
     * Gets the value of the operationsType property.
     * 
     * @return
     *     possible object is
     *     {@link OperationsTypeType }
     *     
     */
    public OperationsTypeType getOperationsType() {
        return operationsType;
    }

    /**
     * Sets the value of the operationsType property.
     * 
     * @param value
     *     allowed object is
     *     {@link OperationsTypeType }
     *     
     */
    public void setOperationsType(OperationsTypeType value) {
        this.operationsType = value;
    }

    /**
     * Gets the value of the momFunction property.
     * 
     * @return
     *     possible object is
     *     {@link MOMFunctionType }
     *     
     */
    public MOMFunctionType getMOMFunction() {
        return momFunction;
    }

    /**
     * Sets the value of the momFunction property.
     * 
     * @param value
     *     allowed object is
     *     {@link MOMFunctionType }
     *     
     */
    public void setMOMFunction(MOMFunctionType value) {
        this.momFunction = value;
    }

    /**
     * Gets the value of the enterpriseFunction property.
     * 
     * @return
     *     possible object is
     *     {@link EnterpriseFunctionType }
     *     
     */
    public EnterpriseFunctionType getEnterpriseFunction() {
        return enterpriseFunction;
    }

    /**
     * Sets the value of the enterpriseFunction property.
     * 
     * @param value
     *     allowed object is
     *     {@link EnterpriseFunctionType }
     *     
     */
    public void setEnterpriseFunction(EnterpriseFunctionType value) {
        this.enterpriseFunction = value;
    }

    /**
     * Gets the value of the category property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the category property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCategory().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link IdentifierType }
     * 
     * 
     */
    public List<IdentifierType> getCategory() {
        if (category == null) {
            category = new ArrayList<IdentifierType>();
        }
        return this.category;
    }

    /**
     * Gets the value of the acknowledgement property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the acknowledgement property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAcknowledgement().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link IdentifierType }
     * 
     * 
     */
    public List<IdentifierType> getAcknowledgement() {
        if (acknowledgement == null) {
            acknowledgement = new ArrayList<IdentifierType>();
        }
        return this.acknowledgement;
    }

    /**
     * Gets the value of the source property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the source property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSource().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link IdentifierType }
     * 
     * 
     */
    public List<IdentifierType> getSource() {
        if (source == null) {
            source = new ArrayList<IdentifierType>();
        }
        return this.source;
    }

    /**
     * Gets the value of the operationsEventDefinitionChild property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the operationsEventDefinitionChild property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOperationsEventDefinitionChild().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link OperationsEventDefinitionType }
     * 
     * 
     */
    public List<OperationsEventDefinitionType> getOperationsEventDefinitionChild() {
        if (operationsEventDefinitionChild == null) {
            operationsEventDefinitionChild = new ArrayList<OperationsEventDefinitionType>();
        }
        return this.operationsEventDefinitionChild;
    }

    /**
     * Gets the value of the operationsEventDefinitionProperty property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the operationsEventDefinitionProperty property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOperationsEventDefinitionProperty().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link OperationsEventClassPropertyType }
     * 
     * 
     */
    public List<OperationsEventClassPropertyType> getOperationsEventDefinitionProperty() {
        if (operationsEventDefinitionProperty == null) {
            operationsEventDefinitionProperty = new ArrayList<OperationsEventClassPropertyType>();
        }
        return this.operationsEventDefinitionProperty;
    }

    /**
     * Gets the value of the operationsEventClassID property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the operationsEventClassID property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOperationsEventClassID().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link IdentifierType }
     * 
     * 
     */
    public List<IdentifierType> getOperationsEventClassID() {
        if (operationsEventClassID == null) {
            operationsEventClassID = new ArrayList<IdentifierType>();
        }
        return this.operationsEventClassID;
    }

    /**
     * Gets the value of the opsEventDefinitionRecordSpecification property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the opsEventDefinitionRecordSpecification property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOpsEventDefinitionRecordSpecification().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link OperationsRecordSpecTemplateType }
     * 
     * 
     */
    public List<OperationsRecordSpecTemplateType> getOpsEventDefinitionRecordSpecification() {
        if (opsEventDefinitionRecordSpecification == null) {
            opsEventDefinitionRecordSpecification = new ArrayList<OperationsRecordSpecTemplateType>();
        }
        return this.opsEventDefinitionRecordSpecification;
    }

}
