//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.11.10 at 09:10:55 AM CET 
//


package org.mesa.xml.b2mml;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.Duration;


/**
 * <p>Java class for OpSegmentRequirementType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="OpSegmentRequirementType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ID" type="{http://www.mesa.org/xml/B2MML}IdentifierType"/>
 *         &lt;element name="Description" type="{http://www.mesa.org/xml/B2MML}DescriptionType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Version" type="{http://www.mesa.org/xml/B2MML}IdentifierType" minOccurs="0"/>
 *         &lt;element name="EarliestStartTime" type="{http://www.mesa.org/xml/B2MML}DateTimeType" minOccurs="0"/>
 *         &lt;element name="LatestEndTime" type="{http://www.mesa.org/xml/B2MML}DateTimeType" minOccurs="0"/>
 *         &lt;element name="HierarchyScope" type="{http://www.mesa.org/xml/B2MML}HierarchyScopeType" minOccurs="0"/>
 *         &lt;element name="OperationsType" type="{http://www.mesa.org/xml/B2MML}OperationsTypeType" minOccurs="0"/>
 *         &lt;element name="ProcessSegmentID" type="{http://www.mesa.org/xml/B2MML}IdentifierType"/>
 *         &lt;element name="Duration" type="{http://www.mesa.org/xml/B2MML}DurationType" minOccurs="0"/>
 *         &lt;element name="OperationsDefinitionID" type="{http://www.mesa.org/xml/B2MML}IdentifierType"/>
 *         &lt;element name="OperationsSegmentID" type="{http://www.mesa.org/xml/B2MML}IdentifierType"/>
 *         &lt;element name="SegmentState" type="{http://www.mesa.org/xml/B2MML}RequestStateType" minOccurs="0"/>
 *         &lt;element name="SegmentParameter" type="{http://www.mesa.org/xml/B2MML}ParameterType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="PersonnelRequirement" type="{http://www.mesa.org/xml/B2MML}OpPersonnelRequirementType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="EquipmentRequirement" type="{http://www.mesa.org/xml/B2MML}OpEquipmentRequirementType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="PhysicalAssetRequirement" type="{http://www.mesa.org/xml/B2MML}OpPhysicalAssetRequirementType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="MaterialRequirement" type="{http://www.mesa.org/xml/B2MML}OpMaterialRequirementType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="SegmentRequirementChild" type="{http://www.mesa.org/xml/B2MML}OpSegmentRequirementType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="RequestedSegmentResponse" type="{http://www.mesa.org/xml/B2MML}OpSegmentResponseType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="RequiredByRequestedSegmentResponse" type="{http://www.mesa.org/xml/B2MML}RequiredByRequestedSegmentResponseType" minOccurs="0"/>
 *         &lt;group ref="{http://www.mesa.org/xml/B2MML-AllExtensions}OpSegmentRequirement" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OpSegmentRequirementType", propOrder = {
    "id",
    "description",
    "version",
    "earliestStartTime",
    "latestEndTime",
    "hierarchyScope",
    "operationsType",
    "processSegmentID",
    "duration",
    "operationsDefinitionID",
    "operationsSegmentID",
    "segmentState",
    "segmentParameter",
    "personnelRequirement",
    "equipmentRequirement",
    "physicalAssetRequirement",
    "materialRequirement",
    "segmentRequirementChild",
    "requestedSegmentResponse",
    "requiredByRequestedSegmentResponse"
})
public class OpSegmentRequirementType {

    @XmlElement(name = "ID", required = true)
    protected IdentifierType id;
    @XmlElement(name = "Description")
    protected List<DescriptionType> description;
    @XmlElement(name = "Version")
    protected IdentifierType version;
    @XmlElement(name = "EarliestStartTime")
    protected DateTimeType earliestStartTime;
    @XmlElement(name = "LatestEndTime")
    protected DateTimeType latestEndTime;
    @XmlElement(name = "HierarchyScope")
    protected HierarchyScopeType hierarchyScope;
    @XmlElement(name = "OperationsType")
    protected OperationsTypeType operationsType;
    @XmlElement(name = "ProcessSegmentID", required = true)
    protected IdentifierType processSegmentID;
    @XmlElement(name = "Duration")
    protected Duration duration;
    @XmlElement(name = "OperationsDefinitionID", required = true)
    protected IdentifierType operationsDefinitionID;
    @XmlElement(name = "OperationsSegmentID", required = true)
    protected IdentifierType operationsSegmentID;
    @XmlElement(name = "SegmentState")
    protected RequestStateType segmentState;
    @XmlElement(name = "SegmentParameter")
    protected List<ParameterType> segmentParameter;
    @XmlElement(name = "PersonnelRequirement")
    protected List<OpPersonnelRequirementType> personnelRequirement;
    @XmlElement(name = "EquipmentRequirement")
    protected List<OpEquipmentRequirementType> equipmentRequirement;
    @XmlElement(name = "PhysicalAssetRequirement")
    protected List<OpPhysicalAssetRequirementType> physicalAssetRequirement;
    @XmlElement(name = "MaterialRequirement")
    protected List<OpMaterialRequirementType> materialRequirement;
    @XmlElement(name = "SegmentRequirementChild")
    protected List<OpSegmentRequirementType> segmentRequirementChild;
    @XmlElement(name = "RequestedSegmentResponse")
    protected List<OpSegmentResponseType> requestedSegmentResponse;
    @XmlElement(name = "RequiredByRequestedSegmentResponse")
    protected RequiredByRequestedSegmentResponseType requiredByRequestedSegmentResponse;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link IdentifierType }
     *     
     */
    public IdentifierType getID() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link IdentifierType }
     *     
     */
    public void setID(IdentifierType value) {
        this.id = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the description property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDescription().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DescriptionType }
     * 
     * 
     */
    public List<DescriptionType> getDescription() {
        if (description == null) {
            description = new ArrayList<DescriptionType>();
        }
        return this.description;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link IdentifierType }
     *     
     */
    public IdentifierType getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link IdentifierType }
     *     
     */
    public void setVersion(IdentifierType value) {
        this.version = value;
    }

    /**
     * Gets the value of the earliestStartTime property.
     * 
     * @return
     *     possible object is
     *     {@link DateTimeType }
     *     
     */
    public DateTimeType getEarliestStartTime() {
        return earliestStartTime;
    }

    /**
     * Sets the value of the earliestStartTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateTimeType }
     *     
     */
    public void setEarliestStartTime(DateTimeType value) {
        this.earliestStartTime = value;
    }

    /**
     * Gets the value of the latestEndTime property.
     * 
     * @return
     *     possible object is
     *     {@link DateTimeType }
     *     
     */
    public DateTimeType getLatestEndTime() {
        return latestEndTime;
    }

    /**
     * Sets the value of the latestEndTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateTimeType }
     *     
     */
    public void setLatestEndTime(DateTimeType value) {
        this.latestEndTime = value;
    }

    /**
     * Gets the value of the hierarchyScope property.
     * 
     * @return
     *     possible object is
     *     {@link HierarchyScopeType }
     *     
     */
    public HierarchyScopeType getHierarchyScope() {
        return hierarchyScope;
    }

    /**
     * Sets the value of the hierarchyScope property.
     * 
     * @param value
     *     allowed object is
     *     {@link HierarchyScopeType }
     *     
     */
    public void setHierarchyScope(HierarchyScopeType value) {
        this.hierarchyScope = value;
    }

    /**
     * Gets the value of the operationsType property.
     * 
     * @return
     *     possible object is
     *     {@link OperationsTypeType }
     *     
     */
    public OperationsTypeType getOperationsType() {
        return operationsType;
    }

    /**
     * Sets the value of the operationsType property.
     * 
     * @param value
     *     allowed object is
     *     {@link OperationsTypeType }
     *     
     */
    public void setOperationsType(OperationsTypeType value) {
        this.operationsType = value;
    }

    /**
     * Gets the value of the processSegmentID property.
     * 
     * @return
     *     possible object is
     *     {@link IdentifierType }
     *     
     */
    public IdentifierType getProcessSegmentID() {
        return processSegmentID;
    }

    /**
     * Sets the value of the processSegmentID property.
     * 
     * @param value
     *     allowed object is
     *     {@link IdentifierType }
     *     
     */
    public void setProcessSegmentID(IdentifierType value) {
        this.processSegmentID = value;
    }

    /**
     * Gets the value of the duration property.
     * 
     * @return
     *     possible object is
     *     {@link Duration }
     *     
     */
    public Duration getDuration() {
        return duration;
    }

    /**
     * Sets the value of the duration property.
     * 
     * @param value
     *     allowed object is
     *     {@link Duration }
     *     
     */
    public void setDuration(Duration value) {
        this.duration = value;
    }

    /**
     * Gets the value of the operationsDefinitionID property.
     * 
     * @return
     *     possible object is
     *     {@link IdentifierType }
     *     
     */
    public IdentifierType getOperationsDefinitionID() {
        return operationsDefinitionID;
    }

    /**
     * Sets the value of the operationsDefinitionID property.
     * 
     * @param value
     *     allowed object is
     *     {@link IdentifierType }
     *     
     */
    public void setOperationsDefinitionID(IdentifierType value) {
        this.operationsDefinitionID = value;
    }

    /**
     * Gets the value of the operationsSegmentID property.
     * 
     * @return
     *     possible object is
     *     {@link IdentifierType }
     *     
     */
    public IdentifierType getOperationsSegmentID() {
        return operationsSegmentID;
    }

    /**
     * Sets the value of the operationsSegmentID property.
     * 
     * @param value
     *     allowed object is
     *     {@link IdentifierType }
     *     
     */
    public void setOperationsSegmentID(IdentifierType value) {
        this.operationsSegmentID = value;
    }

    /**
     * Gets the value of the segmentState property.
     * 
     * @return
     *     possible object is
     *     {@link RequestStateType }
     *     
     */
    public RequestStateType getSegmentState() {
        return segmentState;
    }

    /**
     * Sets the value of the segmentState property.
     * 
     * @param value
     *     allowed object is
     *     {@link RequestStateType }
     *     
     */
    public void setSegmentState(RequestStateType value) {
        this.segmentState = value;
    }

    /**
     * Gets the value of the segmentParameter property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the segmentParameter property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSegmentParameter().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ParameterType }
     * 
     * 
     */
    public List<ParameterType> getSegmentParameter() {
        if (segmentParameter == null) {
            segmentParameter = new ArrayList<ParameterType>();
        }
        return this.segmentParameter;
    }

    /**
     * Gets the value of the personnelRequirement property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the personnelRequirement property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPersonnelRequirement().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link OpPersonnelRequirementType }
     * 
     * 
     */
    public List<OpPersonnelRequirementType> getPersonnelRequirement() {
        if (personnelRequirement == null) {
            personnelRequirement = new ArrayList<OpPersonnelRequirementType>();
        }
        return this.personnelRequirement;
    }

    /**
     * Gets the value of the equipmentRequirement property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the equipmentRequirement property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEquipmentRequirement().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link OpEquipmentRequirementType }
     * 
     * 
     */
    public List<OpEquipmentRequirementType> getEquipmentRequirement() {
        if (equipmentRequirement == null) {
            equipmentRequirement = new ArrayList<OpEquipmentRequirementType>();
        }
        return this.equipmentRequirement;
    }

    /**
     * Gets the value of the physicalAssetRequirement property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the physicalAssetRequirement property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPhysicalAssetRequirement().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link OpPhysicalAssetRequirementType }
     * 
     * 
     */
    public List<OpPhysicalAssetRequirementType> getPhysicalAssetRequirement() {
        if (physicalAssetRequirement == null) {
            physicalAssetRequirement = new ArrayList<OpPhysicalAssetRequirementType>();
        }
        return this.physicalAssetRequirement;
    }

    /**
     * Gets the value of the materialRequirement property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the materialRequirement property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMaterialRequirement().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link OpMaterialRequirementType }
     * 
     * 
     */
    public List<OpMaterialRequirementType> getMaterialRequirement() {
        if (materialRequirement == null) {
            materialRequirement = new ArrayList<OpMaterialRequirementType>();
        }
        return this.materialRequirement;
    }

    /**
     * Gets the value of the segmentRequirementChild property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the segmentRequirementChild property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSegmentRequirementChild().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link OpSegmentRequirementType }
     * 
     * 
     */
    public List<OpSegmentRequirementType> getSegmentRequirementChild() {
        if (segmentRequirementChild == null) {
            segmentRequirementChild = new ArrayList<OpSegmentRequirementType>();
        }
        return this.segmentRequirementChild;
    }

    /**
     * Gets the value of the requestedSegmentResponse property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the requestedSegmentResponse property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRequestedSegmentResponse().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link OpSegmentResponseType }
     * 
     * 
     */
    public List<OpSegmentResponseType> getRequestedSegmentResponse() {
        if (requestedSegmentResponse == null) {
            requestedSegmentResponse = new ArrayList<OpSegmentResponseType>();
        }
        return this.requestedSegmentResponse;
    }

    /**
     * Gets the value of the requiredByRequestedSegmentResponse property.
     * 
     * @return
     *     possible object is
     *     {@link RequiredByRequestedSegmentResponseType }
     *     
     */
    public RequiredByRequestedSegmentResponseType getRequiredByRequestedSegmentResponse() {
        return requiredByRequestedSegmentResponse;
    }

    /**
     * Sets the value of the requiredByRequestedSegmentResponse property.
     * 
     * @param value
     *     allowed object is
     *     {@link RequiredByRequestedSegmentResponseType }
     *     
     */
    public void setRequiredByRequestedSegmentResponse(RequiredByRequestedSegmentResponseType value) {
        this.requiredByRequestedSegmentResponse = value;
    }

}
