//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.11.10 at 09:10:55 AM CET 
//


package org.mesa.xml.b2mml;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ResourceNetworkConnectionType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ResourceNetworkConnectionType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ID" type="{http://www.mesa.org/xml/B2MML}IdentifierType"/>
 *         &lt;element name="Description" type="{http://www.mesa.org/xml/B2MML}DescriptionType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="ResourceNetworkConnectionTypeID" type="{http://www.mesa.org/xml/B2MML}IdentifierType"/>
 *         &lt;element name="FromResourceReference" type="{http://www.mesa.org/xml/B2MML}ResourceReferenceType"/>
 *         &lt;element name="ToResourceReference" type="{http://www.mesa.org/xml/B2MML}ResourceReferenceType"/>
 *         &lt;element name="RNCProperty" type="{http://www.mesa.org/xml/B2MML}RNCPropertyType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;group ref="{http://www.mesa.org/xml/B2MML-AllExtensions}ResourceNetworkConnection" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ResourceNetworkConnectionType", propOrder = {
    "id",
    "description",
    "resourceNetworkConnectionTypeID",
    "fromResourceReference",
    "toResourceReference",
    "rncProperty"
})
public class ResourceNetworkConnectionType {

    @XmlElement(name = "ID", required = true)
    protected IdentifierType id;
    @XmlElement(name = "Description")
    protected List<DescriptionType> description;
    @XmlElement(name = "ResourceNetworkConnectionTypeID", required = true)
    protected IdentifierType resourceNetworkConnectionTypeID;
    @XmlElement(name = "FromResourceReference", required = true)
    protected ResourceReferenceType fromResourceReference;
    @XmlElement(name = "ToResourceReference", required = true)
    protected ResourceReferenceType toResourceReference;
    @XmlElement(name = "RNCProperty")
    protected List<RNCPropertyType> rncProperty;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link IdentifierType }
     *     
     */
    public IdentifierType getID() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link IdentifierType }
     *     
     */
    public void setID(IdentifierType value) {
        this.id = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the description property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDescription().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DescriptionType }
     * 
     * 
     */
    public List<DescriptionType> getDescription() {
        if (description == null) {
            description = new ArrayList<DescriptionType>();
        }
        return this.description;
    }

    /**
     * Gets the value of the resourceNetworkConnectionTypeID property.
     * 
     * @return
     *     possible object is
     *     {@link IdentifierType }
     *     
     */
    public IdentifierType getResourceNetworkConnectionTypeID() {
        return resourceNetworkConnectionTypeID;
    }

    /**
     * Sets the value of the resourceNetworkConnectionTypeID property.
     * 
     * @param value
     *     allowed object is
     *     {@link IdentifierType }
     *     
     */
    public void setResourceNetworkConnectionTypeID(IdentifierType value) {
        this.resourceNetworkConnectionTypeID = value;
    }

    /**
     * Gets the value of the fromResourceReference property.
     * 
     * @return
     *     possible object is
     *     {@link ResourceReferenceType }
     *     
     */
    public ResourceReferenceType getFromResourceReference() {
        return fromResourceReference;
    }

    /**
     * Sets the value of the fromResourceReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link ResourceReferenceType }
     *     
     */
    public void setFromResourceReference(ResourceReferenceType value) {
        this.fromResourceReference = value;
    }

    /**
     * Gets the value of the toResourceReference property.
     * 
     * @return
     *     possible object is
     *     {@link ResourceReferenceType }
     *     
     */
    public ResourceReferenceType getToResourceReference() {
        return toResourceReference;
    }

    /**
     * Sets the value of the toResourceReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link ResourceReferenceType }
     *     
     */
    public void setToResourceReference(ResourceReferenceType value) {
        this.toResourceReference = value;
    }

    /**
     * Gets the value of the rncProperty property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the rncProperty property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRNCProperty().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RNCPropertyType }
     * 
     * 
     */
    public List<RNCPropertyType> getRNCProperty() {
        if (rncProperty == null) {
            rncProperty = new ArrayList<RNCPropertyType>();
        }
        return this.rncProperty;
    }

}
