//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.11.10 at 09:10:55 AM CET 
//


package org.mesa.xml.b2mml;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for WorkflowSpecificationConnectionType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="WorkflowSpecificationConnectionType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ID" type="{http://www.mesa.org/xml/B2MML}IdentifierType"/>
 *         &lt;element name="Description" type="{http://www.mesa.org/xml/B2MML}DescriptionType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="WorkflowSpecificationConnectionTypeID" type="{http://www.mesa.org/xml/B2MML}IdentifierType" minOccurs="0"/>
 *         &lt;element name="FromWSNodeID" type="{http://www.mesa.org/xml/B2MML}DescriptionType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="ToWSNodeID" type="{http://www.mesa.org/xml/B2MML}DescriptionType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Dependency" type="{http://www.mesa.org/xml/B2MML}DependencyType"/>
 *         &lt;element name="DependencyFactor" type="{http://www.mesa.org/xml/B2MML}ValueType" minOccurs="0"/>
 *         &lt;element name="WorkflowSpecificationConnectionProperty" type="{http://www.mesa.org/xml/B2MML}WorkflowSpecificationConnectionPropertyType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;group ref="{http://www.mesa.org/xml/B2MML-AllExtensions}WorkflowSpecificationConnection" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "WorkflowSpecificationConnectionType", propOrder = {
    "id",
    "description",
    "workflowSpecificationConnectionTypeID",
    "fromWSNodeID",
    "toWSNodeID",
    "dependency",
    "dependencyFactor",
    "workflowSpecificationConnectionProperty"
})
public class WorkflowSpecificationConnectionType {

    @XmlElement(name = "ID", required = true)
    protected IdentifierType id;
    @XmlElement(name = "Description")
    protected List<DescriptionType> description;
    @XmlElement(name = "WorkflowSpecificationConnectionTypeID")
    protected IdentifierType workflowSpecificationConnectionTypeID;
    @XmlElement(name = "FromWSNodeID")
    protected List<DescriptionType> fromWSNodeID;
    @XmlElement(name = "ToWSNodeID")
    protected List<DescriptionType> toWSNodeID;
    @XmlElement(name = "Dependency", required = true)
    protected DependencyType dependency;
    @XmlElement(name = "DependencyFactor")
    protected ValueType dependencyFactor;
    @XmlElement(name = "WorkflowSpecificationConnectionProperty")
    protected List<WorkflowSpecificationConnectionPropertyType> workflowSpecificationConnectionProperty;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link IdentifierType }
     *     
     */
    public IdentifierType getID() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link IdentifierType }
     *     
     */
    public void setID(IdentifierType value) {
        this.id = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the description property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDescription().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DescriptionType }
     * 
     * 
     */
    public List<DescriptionType> getDescription() {
        if (description == null) {
            description = new ArrayList<DescriptionType>();
        }
        return this.description;
    }

    /**
     * Gets the value of the workflowSpecificationConnectionTypeID property.
     * 
     * @return
     *     possible object is
     *     {@link IdentifierType }
     *     
     */
    public IdentifierType getWorkflowSpecificationConnectionTypeID() {
        return workflowSpecificationConnectionTypeID;
    }

    /**
     * Sets the value of the workflowSpecificationConnectionTypeID property.
     * 
     * @param value
     *     allowed object is
     *     {@link IdentifierType }
     *     
     */
    public void setWorkflowSpecificationConnectionTypeID(IdentifierType value) {
        this.workflowSpecificationConnectionTypeID = value;
    }

    /**
     * Gets the value of the fromWSNodeID property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the fromWSNodeID property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFromWSNodeID().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DescriptionType }
     * 
     * 
     */
    public List<DescriptionType> getFromWSNodeID() {
        if (fromWSNodeID == null) {
            fromWSNodeID = new ArrayList<DescriptionType>();
        }
        return this.fromWSNodeID;
    }

    /**
     * Gets the value of the toWSNodeID property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the toWSNodeID property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getToWSNodeID().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DescriptionType }
     * 
     * 
     */
    public List<DescriptionType> getToWSNodeID() {
        if (toWSNodeID == null) {
            toWSNodeID = new ArrayList<DescriptionType>();
        }
        return this.toWSNodeID;
    }

    /**
     * Gets the value of the dependency property.
     * 
     * @return
     *     possible object is
     *     {@link DependencyType }
     *     
     */
    public DependencyType getDependency() {
        return dependency;
    }

    /**
     * Sets the value of the dependency property.
     * 
     * @param value
     *     allowed object is
     *     {@link DependencyType }
     *     
     */
    public void setDependency(DependencyType value) {
        this.dependency = value;
    }

    /**
     * Gets the value of the dependencyFactor property.
     * 
     * @return
     *     possible object is
     *     {@link ValueType }
     *     
     */
    public ValueType getDependencyFactor() {
        return dependencyFactor;
    }

    /**
     * Sets the value of the dependencyFactor property.
     * 
     * @param value
     *     allowed object is
     *     {@link ValueType }
     *     
     */
    public void setDependencyFactor(ValueType value) {
        this.dependencyFactor = value;
    }

    /**
     * Gets the value of the workflowSpecificationConnectionProperty property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the workflowSpecificationConnectionProperty property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getWorkflowSpecificationConnectionProperty().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link WorkflowSpecificationConnectionPropertyType }
     * 
     * 
     */
    public List<WorkflowSpecificationConnectionPropertyType> getWorkflowSpecificationConnectionProperty() {
        if (workflowSpecificationConnectionProperty == null) {
            workflowSpecificationConnectionProperty = new ArrayList<WorkflowSpecificationConnectionPropertyType>();
        }
        return this.workflowSpecificationConnectionProperty;
    }

}
